language: r
dist: trusty
cache: packages

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

r:
  - oldrel
  - release
  - devel
