
language: r
warnings_are_errors: true
sudo: required

r_binary_packages:
  - sp

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel
