language: r
cache: packages
dist: trusty
sudo: required

before_install:
 # - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
#  - sudo apt-get --yes --force-yes update -qq
 # - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

  - sudo apt-get install libv8-dev
  - sudo apt-get install aptitude -y
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

r_packages:
  - rgdal

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

r:
  - oldrel
  - release
  - devel
