language: r
dist: trusty
sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos-dev libgdal-dev

notifications:
  email:
    on_success: change
    on_failure: change

r:
  - oldrel
  - release
  - devel
